### ISSUE TITLE
Vyhledávání -> subscribe, lupa

### ISSUE THREAD

**Issue by Kedrigern** [pirati-web/pirati.cz#10]
Vyhledávání zaměnit za subscribe a samotné vyhledávání udělat na rozklik

**Comment by Kedrigern** [comment]
První část implementoána. Teď ještě zprovoznit subscribe a vyhledávání pokud nemáme stránku v našeptávači.

**Comment by Kedrigern** [comment]
Marek Paris navrhl dát vyhledávání do horní černé lišty a mail subsribe tam, kde je vyhledávání.

Avšak nejde mi to nastylovat. Zatím nechvávám jen vyhledávání.

**Comment by stanley89** [comment]
Takže budou dva inputy těsně nad sebou? To bude nepřehledné.
