### ISSUE TITLE
Kontakt (koordinátor) na stránce kraje

### ISSUE THREAD

**Issue by Fafrin** [pirati-web/pirati.cz#111]
Na stránce kraje nám pořád nefunguje koordinátor:
https://www.pirati.cz/pripoj-se/olomoucko/
Na jiných nefunguje lépe, takže se nemám moc kde inspirovat.

Tuším chybu někde tu: 
https://github.com/pirati-web/pirati.cz/blob/gh-pages/_includes/js/custom.js

Ale zatím jsem nebyl sto nahlédnout jak na to.

**Comment by Kedrigern** [comment]
Už funguje, v jiných krajích nefunguje, protože nemají profil.

**Comment by jmichalek** [comment]
Ahoj, tato fotka je zbytečně velká...
https://www.pirati.cz/assets/img/people/michal-gill.jpg

----
Mgr. et Mgr. Jakub Michálek,
předseda klubu Pirátů v zastupitelstvu hl. m. Prahy
jakub.michalek@pirati.cz, tel. 775 978 550

Česká pirátská strana
krajské sdružení Pirátů Praha
http://praha.pirati.cz

Upozornění: Týká-li se tato e-mailová zpráva jednání o smlouvě, bere její
adresát na vědomí, že v České pirátské straně podléhá uzavírání smluv
vnitřním předpisům a důvodné očekávání uzavření smlouvy je tak možné až po
souhlasu pověřeného orgánu. Vylučujeme přijetí nabídky s dodatkem nebo
odchylkou.

2017-08-11 16:54 GMT+02:00 Ondřej Profant <notifications@github.com>:
