### ISSUE TITLE
Mobilní design

### ISSUE THREAD

**Issue by Kedrigern** [pirati-web/pirati.cz#12]
V submenu (šedé, na `připoj se`, `o nás` a `program`) je obrázek, který zbytečně překáží v mobilní verzi.  Bylo by dobré ho schovat pro mobily.

**Comment by Kedrigern** [comment]
Obrázek je nadefinován jako pozadí v css: top-sub-nav.scss

**Comment by madbeyk** [comment]
nemuzu ted nikde moc testovat,
v
.#{$tsb-ns}c-top-sub-nav .#{$tsb-ns}c-top-sub-nav-inner {
pridat nebo prizpusobit breakpointy tak aby v mobile down bylo
display:none;
misto
padding: 35px 1.25rem;
tim padem zmizi ta image v backgroundu
