### ISSUE TITLE
Připoj se

### ISSUE THREAD

**Issue by stanley89** [pirati-web/pirati.cz#13]
Na stránce https://pirati-web.github.io/pirati.cz/pripoj-se/

- Co se stane po vyplnění formuláře? Chtělo by to tam napsat. Určitě se člověk na základě vyplnění tohoto automaticky nestává členem (vlastně ani regp.)
- Hláška "This field is required." není přeložená

**Comment by lipoh** [comment]
Angličtina je rozbitým js, opravím dnes. Je možné, že se to rozbilo při refactoringu té stránky.

**Comment by stanley89** [comment]
díky, a ještě na té stránce nefunguje odkaz na vyplň dotazník

**Comment by Kedrigern** [comment]
Dorazník odstraněn.
