### ISSUE TITLE
Odkazy na homepage

### ISSUE THREAD

**Issue by stanley89** [pirati-web/pirati.cz#14]
- U hlavního článku by bylo vhodné, aby byl odkazem celý obrázek
- U jednotlivých článků by měl být odkazem i obrázek
- U Lidí také jméno a obrázek

**Comment by Kedrigern** [comment]
- [ ] U hlavního článku by bylo vhodné, aby byl odkazem celý obrázek
- [X] U jednotlivých článků by měl být odkazem i obrázek
- [X] U Lidí také jméno a obrázek

by 6e40bfe
