### ISSUE TITLE
Vnořené odrážky

### ISSUE THREAD

**Issue by Kedrigern** [pirati-web/pirati.cz#156]
Vnořené odrážky se zobrazují na stejné úrovni. Např na stránce: https://www.pirati.cz/program/temata/digitalni-cesko/

**Příklad**:

- akceptace dlouhodobé vize digitalizace státu napříč úřady a majoritními politickými silami
- změna procesů zajišťující agendy
- minimálně nutná změna zákonů, vyhlášek a metodik umožňující a podporující digitalizaci agend
- proobčaský přístup
    - pochopení občana jako klienta, zákazníka
    - primární je uspokojení potřeb občana, nikoliv zjednodušení práce úředníka
- informační otevřenost

**Zdrojový kod příkladu (vygenerováno je správně):**
```html
<ul>
  <li>akceptace dlouhodobé vize digitalizace státu napříč úřady a majoritními politickými silami</li>
  <li>změna procesů zajišťující agendy</li>
  <li>minimálně nutná změna zákonů, vyhlášek a metodik umožňující a podporující digitalizaci agend</li>
  <li>proobčaský přístup
    <ol>
      <li>pochopení občana jako klienta, zákazníka</li>
      <li>primární je uspokojení potřeb občana, nikoliv zjednodušení práce úředníka</li>
    </ol>
  </li>
  <li>informační otevřenost</li>
```

**Comment by milladekilla** [comment]
https://github.com/pirati-web/pirati.cz/pull/164

**Comment by milladekilla** [comment]
Principielne je celkem neobratne pouzivat OL seznamy a prestylovavat je jako UL  ... OL = ordered list = cislovany, v merge requestu jsem to zrusil. Pokud by se do vnoreneho seznamu meli dodat jine odrazky, tak to je potreba dodelat.

**Comment by Kedrigern** [comment]
Super, už to funguje. Akorát jsou celkově odrážky posunuty před zbylý text (příliš vlevo):

Viz https://www.pirati.cz/program/temata/digitalni-cesko/

**Comment by DejfCold** [comment]
Omlouvám se, že se vecpávám, ale pokud se mohu pokusit poradi, tak v:
main.css
```
.c-BasicPage-content ol, .c-BasicPage-content ul {
    margin-bottom: 1.5em;
    **margin-left: 1.5em;**
}
```

**Comment by Kedrigern** [comment]
Děkuji, opravil jsem.
