### ISSUE TITLE
Uspořádat vzkazy v láhvi

### ISSUE THREAD

**Issue by Fafrin** [pirati-web/pirati.cz#186]
Na téhla stránce https://www.pirati.cz/plavba/
jsou vzkazy v láhvi, kteté jsou ve šňůře pod sebou.
Kdyby je někdo dokázal upravit tak, aby se responzivně vyskládali po celé šířce, bylo by to super.

**Comment by cironis-adam** [comment]
Nemám access rights na novou branch, tak aspoň takhle:

> File: plava/index.html

`
<div class="row">
  <div class="large-3 large-offset-4 colums">
    <h1 class="text-center" id="vzkazy">Vzkazy v lahvi</h1>
  </div>
  {% for vzkaz in site.data.vzkazy %}
  <div class="row">
  <div class="large-3 small-12 columns">
    <div class="callout">
    {{ vzkaz.note }}<br>-- {{ vzkaz.name }}
    </div>
  </div>
</div>
  {% endfor %}
</div>
`

**Comment by stanley89** [comment]
Prosím případně o pull request, to muže každý :-)

**Comment by Fafrin** [comment]
[pull](https://github.com/pirati-web/pirati.cz/pull/193)

Ale jako výsledek vidím jen, že jsou všechny ve sloupci vlevo, místo na středu.

**Comment by cironis-adam** [comment]
Měl by fixnout #196

**Comment by Fafrin** [comment]
Určitě lepší, ještě by se možná dalo to nějak srazit nebo vylepšit, ale za mě dobré.
