### ISSUE TITLE
flicker

### ISSUE THREAD

**Issue by jitka** [pirati-web/pirati.cz#189]
Bylo by fajn mit v nejvíšší hlavíčce webu mezi sociálními sítěmi i flicker.
https://www.flickr.com/photos/pirati/

**Comment by Fafrin** [comment]
existuje pro něj ikona?

**Comment by madbeyk** [comment]
ikona ve font awesome je ...
https://fontawesome.com/v4.7.0/icon/flickr/
`<i class="fa fa-flickr" aria-hidden="true"></i>`

**Comment by madbeyk** [comment]
solved ,,, #330
