### ISSUE TITLE
Kandidátky na mobilu

### ISSUE THREAD

**Issue by Kedrigern** [pirati-web/pirati.cz#203]
Kandidátky na mobilu (Android) nevypadají moc dobře. IMHO by bylo lepší zrušit dva sloupce. A fotku mít jen pod jménem.

**Comment by runn1ng** [comment]
Nejenom "nevypadají dobře", ale jsou skoro nepoužitelné.

Při skrolování dolu začne "jezdit" hlava kandidáta směrem dolu, a překryje text pod tím.

Screenshoty:

![screenshot_20171012-191406](https://user-images.githubusercontent.com/104945/31509456-d26c908e-af81-11e7-86d7-d4b9674a8b7f.png)
![screenshot_20171012-191311](https://user-images.githubusercontent.com/104945/31509457-d2923604-af81-11e7-8a0c-0d44eb864ce2.png)

**Comment by Fafrin** [comment]
fixed, ne?

**Comment by runn1ng** [comment]
Jop
