### ISSUE TITLE
Chybné kontakty do senátu

### ISSUE THREAD

**Issue by jachymb** [pirati-web/pirati.cz#208]
Na straně https://www.pirati.cz/lide/libor-michalek/ je uveden senátní email senátora Michálka lmichalek@senat.cz To je ale špatně, správně je michalekl@senat.cz Zkontrolovat i u ostatních senátorů s podporou pirátů.

**Comment by Fafrin** [comment]
https://github.com/pirati-web/pirati.cz/commit/71ca4b6aa51d4236bd6a47f6fba56f3324863c9e

fixed.

ostatní tam nemají senátní, tak jsem to jen proletěl.
