### ISSUE TITLE
Zadat na web poslance

### ISSUE THREAD

**Issue by Fafrin** [pirati-web/pirati.cz#225]
Je třeba vytvořit seznam poslanců klubu, základně přiřazením osob do daných skupin

**Comment by Fafrin** [comment]
Základ: https://github.com/pirati-web/pirati.cz/pull/228

Další se musí dodělat profily

**Comment by MichalKetner** [comment]
Panda here.

**Comment by Kedrigern** [comment]
Jan Loužek na tom již pracuje. Až to bude hotové, tak ještě všem pošle mail, aby si to zkontrolovali.

**Comment by Fafrin** [comment]
@MichalKetner  aneb napiš @Aktron a pomožte si.

**Comment by Fafrin** [comment]
out

**Comment by lnovy** [comment]
Kde jsou podklady plz?

**Comment by Fafrin** [comment]
Ze mě je to hotovo dvěma způsoby a to stačí.
