### ISSUE TITLE
stanovy

### ISSUE THREAD

**Issue by jitka** [pirati-web/pirati.cz#240]
chtělo by to doplnit nějaké iformace pro seo
dotaz googlu "stanovy pirati" házi odkaz na wiki

dotaz stanovy do vyhledávacího políčka na webu nabídné dvě možnosti.
Stanovy Pirátské strany -> fungují
Stanovy České pirátské strany -> 404

**Comment by Kedrigern** [comment]
[Stránka](https://www.pirati.cz/o-nas/stanovy.html) aktualizována 4e6e800b7989d19c42c0708985b13ed9ec801976

**Comment by jitka** [comment]
Prosím o znovuotevření. Oba dva problémy SEO i vnitřní vyhledávání jsou stále replikovatelné.
Jdu se na to teď kouknout.

**Comment by jitka** [comment]
přidala jsem do keyword 'stanovy' snad to bude stačit
