### ISSUE TITLE
snemovna redmine

### ISSUE THREAD

**Issue by jitka** [pirati-web/pirati.cz#299]
U bodu 20 z 20 priorit je v redmine 10% splňeno a to se nepropsalo na pirati.cz/snemovna.

**Comment by milladekilla** [comment]
Kouknu na to

**Comment by milladekilla** [comment]
opraveno v https://github.com/pirati-web/pirati.cz/pull/311

**Comment by jitka** [comment]
Stále je to replikovatelné na stejném příkladě.

**Comment by milladekilla** [comment]
no a divala ses na to v vetvi toho PR nebo na webu? ta vetev neni mergla a ja to v ni vidim spravne

**Comment by jitka** [comment]
sorry jsem slepá
u mě na locale to běží v pohodě, proklikala jsem i další věci koukla na diff a s ondrovým svolením jdu mergnout

**Comment by jitka** [comment]
Propsalo se to na ostrý web, zavírám.
