### ISSUE TITLE
Místní týmy

### ISSUE THREAD

**Issue by Fafrin** [pirati-web/pirati.cz#31]
Chtěl bych se zeptat, jestli je záměr na tomhle webu mít i místní regionální týmy, nebo jestli to by mělo být až na krajském webu.
Díky.

**Comment by Kedrigern** [comment]
Patří to na váš krajský web.

Záměrem je mít na centrálním webu relevantní informace. Žádný spam. 

Čili třeba videotým v současnosti působí hlavně v Praze, ale není myšlen jako pražský. Čili kdokoliv chce pomoci a umí natáčet se ozve tomuto týmu a ten mu sdělí know-how, pomůže nahrát na youtube etc.
