### ISSUE TITLE
undefined method `split' for nil:NilClass v programu pro Místní rozvoj

### ISSUE THREAD

**Issue by Aktron** [pirati-web/pirati.cz#320]
Při spuštění webu lokálně dostávám hlášku Error: could not read file /home/aktron/web/pirati.cz/_teams/program/mistni-rozvoj: undefined method `split' for nil:NilClass

Zkoušel jsem se stránkou dělat různé psí kusy, aby se toto už nedělo ale bohužel nevím, co mám udělat, aby se to začalo chovat slušně. Kdo s tím umí, nechť opraví.

**Comment by madbeyk** [comment]
prozacatek bych zkusil dat .md za nazev souboru ...

**Comment by madbeyk** [comment]
doma jsem to testoval, je to tim ...
jenom nechapu vyznam tech stranek tymu, nevede na ne zadnej proklik z webu, nebo jo?
https://www.pirati.cz/pripoj-se/mistni-rozvoj/

**Comment by Aktron** [comment]
Mergeováno. Snad ok.

Honza

2018-04-06 12:28 GMT+02:00 Madbeyk <notifications@github.com>:

**Comment by Fafrin** [comment]
close?

**Comment by madbeyk** [comment]
yep
