### ISSUE TITLE
/snemovna/tymy -> /tymy

### ISSUE THREAD

**Issue by Fafrin** [pirati-web/pirati.cz#325]
Mohla by se ta stránka přesunout do nějakého neutrálnějšího prostoru.
Proč?
Protože co až bude např. /senat ?
Navíc ty resortní týmy mají být celostranické, ne jen klubu.

**Comment by jitka** [comment]
Mě přijdou meziresortní tými jako věc zákonodárná tj hlavně sněmvna a pak senát, ale celostranicky máme garanty programových bodů. Jestli to dobře chápu tak resortní tými jmenuje poslanecký klub, zatímco garanty celostátní fórum. Navíc jsou stále v platnosti staří a nový garanti a slyšela jsem návrhy, že by se mohli sjednotit a přemenovat na stínové ministry. 

`/tymy` bych schovala pro týmy vytvořené podle organizačního řádu

**Comment by jitka** [comment]
https://helios.pirati.cz/helios/elections/82385433-a277-4dc0-8882-67e200686fb6/view
zatím je to skopírované, jdu požádov co redirect

**Comment by jitka** [comment]
done
