### ISSUE TITLE
Dvě stahovací sekce

### ISSUE THREAD

**Issue by jitka** [pirati-web/pirati.cz#328]
https://www.pirati.cz/ke-stazeni/ - vede na ni odkaz z otevřenost
https://www.pirati.cz/download/ - je výš na googlu
dalši odkazy co na to vedou neznám.
Na kterou z nich by jste to sjednotili?

**Comment by Fafrin** [comment]
Už jsem o tom psal mikimu.
Taky máme odpovídající sekce ,a wiki, které je třeba vhodně provázat: 
https://wiki.pirati.cz/mo/docs/start
https://wiki.pirati.cz/mo/grafika/start
https://wiki.pirati.cz/ao/sablony/start

Apod.

**Comment by jitka** [comment]
jsem pro
1. sloučit to do /download
2. titulka -> zveřejňujeme -> ke stažení  přesměrovat na ten /download

co se týče wiki, tak tam bych zatím nic nedělala, tento web bych nechala pro veřejnost a wiki postupně zmigrovala na jinou wikistránku a použivala jako interní web. Příjde mi dobré mít rozdělení interní web a prezentaci a tady se láme hranice mezi nimi.

(snad si na to najdu dnes čas to udělat)

**Comment by Fafrin** [comment]
Souhlasím.
Hranice mezi veřejnou prezentací a interním prostředím strany se zde láme. A to máme mít a aktuálně máme v podobě web vs, dokuwiki.
Provázanost musí existovat, aby nebyl tlak na duplikace.

**Comment by jitka** [comment]
Už to skoro mám https://github.com/pirati-web/pirati.cz/tree/328-dve-stahovaci-sekce,
jen tam chci přidat redirekci ke-stazeni -> downloads.
Líbí se mi na to tenhle plugin https://github.com/tsmango/jekyll_alias_generator, ale nevím jak přidat plugin aby se to projevilo i u nás. Standa @stanley89  prý zvládne poradit.

**Comment by jitka** [comment]
Pushnula jsem to tam tak jak to je. Redirect uděláme v nginx.
