### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by strideynet** [pirati-web/pirati.cz#354]
Hello from Pirate Party UK,

We are looking to adopt Jekyll in the near future and were wondering what license applies to this repository, as we quite like your theme and wish to adapt it.

Regards,

**Comment by Fafrin** [comment]
Good question.
Web itself in its footer states "(copyleft) Piráti, 2016. Všechna práva vyhlazena. Sdílejte a nechte ostatní sdílet za stejných podmínek." so "(copyleft) Piráti, 2016. All rights eliminated. Share and let be shared by others under same conditions."
https://en.wikipedia.org/wiki/Copyleft

**Comment by strideynet** [comment]
Many thanks. Will share and share alike.
