### ISSUE TITLE
Nezobrazují se vedoucí týmů

### ISSUE THREAD

**Issue by Aktron** [pirati-web/pirati.cz#36]
Na stránkách jednotlivých krajů se neozbrazují obrázky vedoucích týmů. Zůstane tam jenom ikonka chybí obrázek. Ve zdrojáku je předdefinovaná část url vyplněna šablonově, chybí ale konkrétní hodnota. 

Možný zdroj problému:

1. Na stránkách regionů není vyplněn parametr, který by tam obrázky linkoval
2. Při předpokladu že se hodnota pro výše spekulovaný parametr generuje z parametru "leader" a někde později v kódu se odstraní diakritika se něco muselo rozbít na cestě a hodnota se nepropíše.

**Comment by Fafrin** [comment]
obázek vyplněn je, ale s blbou adresou. Navrhl jsem opravu, ale pochybuju, že to bude stačit, protože se neobjevuje ani nic jiného.
Nicméně se mi podařilo najít, která stránka vyrábí stránky krajů.
https://github.com/pirati-web/pirati.cz/edit/gh-pages/_layouts/team.html
Pátrání pokračuje....

**Comment by Fafrin** [comment]
Což vede sem: https://github.com/pirati-web/pirati.cz/blob/gh-pages/_includes/right-bar/bar_teams_summary.html
kde netuším, jestli předání param="contacts" je dobře.

Což snad vede sem: https://github.com/pirati-web/pirati.cz/blob/gh-pages/_includes/people/rbar_profile2.html

#48

**Comment by Kedrigern** [comment]
Celé jsem to přepsal u sebe. Nahodím asi během zítřka: https://github.com/kedrigern/pirati.cz

**Comment by Fafrin** [comment]
mno?

**Comment by Kedrigern** [comment]
Ta noc se protáhla... bohužel jsem se celý týden nezastavil.

**Comment by Fafrin** [comment]
Tak bylo začleněno.
Není to perfektní, ale je to lepší.
Podívám se na formátování.

**Comment by Fafrin** [comment]
Zavřít?
