### ISSUE TITLE
Velký Ivan

### ISSUE THREAD

**Issue by Fafrin** [pirati-web/pirati.cz#378]
Ahoj, nevím jestli je to záměr, nebo co.

Ale na stránce /lide https://www.pirati.cz/lide/
Je teď Ivan zobrazen 2x větší než ostatní.

V předsednictvu je to asi možná záměr, ale při rozbalení seznamu poslanců to už vypadá divně.

To už spíš udělejte něco, co tam zvýrazní v seznamu prvního, nebo nevím.

**Comment by jitka** [comment]
@Aktron to opravil
