### ISSUE TITLE
Fórum na titulku

### ISSUE THREAD

**Issue by Fafrin** [pirati-web/pirati.cz#39]
Uvítal bych v liště odkaz na forum.pirati.cz

Pravděpodobně poté, co provedeme nějakou rekonstrukci fóra ohledně viditelností.

**Comment by jmichalek** [comment]
Ano. Nejprve je třeba fórum dát dokupy, pak na něj můžeme odkazovat. Teď by
to bylo kontraproduktivní.

----
Mgr. et Mgr. Jakub Michálek,
předseda klubu Pirátů v zastupitelstvu hl. m. Prahy
jakub.michalek@pirati.cz, tel. 775 978 550

Česká pirátská strana
krajské sdružení Pirátů Praha
http://praha.pirati.cz

Upozornění: Týká-li se tato e-mailová zpráva jednání o smlouvě, bere její
adresát na vědomí, že v České pirátské straně podléhá uzavírání smluv
vnitřním předpisům a důvodné očekávání uzavření smlouvy je tak možné až po
souhlasu pověřeného orgánu. Vylučujeme přijetí nabídky s dodatkem nebo
odchylkou.

Dne 21. března 2017 18:09 Vojtěch Pikal <notifications@github.com>
napsal(a):
