### ISSUE TITLE
Odkaz na www.piratisestanem.cz nefunguje

### ISSUE THREAD

**Issue by josef-spak** [pirati-web/pirati.cz#393]
V souboru: 
https://github.com/pirati-web/pirati.cz/blob/gh-pages/_posts/2018/2018-08-06-piratska-tramvaj-stara-boleslav.md

je asi potřeba tam přidat https:// jinak se z toho udělá relativní odkaz. Že to teď nefunguje (uživatel dostane 404 na stránce https://www.pirati.cz/tiskove-zpravy/www.piratisestanem.cz ) je vidět zde:

https://www.pirati.cz/tiskove-zpravy/piratska-tramvaj-stara-boleslav.html

Příště prosím otestovat.

**Comment by jitka** [comment]
už to opravili
