### ISSUE TITLE
Kalendář na titulku

### ISSUE THREAD

**Issue by Fafrin** [pirati-web/pirati.cz#40]
Uvítal bych možnost dostat se na velký kalendář https://www.pirati.cz/pripoj-se/kalendar/
I když tam je teda jenom Praha, tak nevím.

Možná místo odkazu na Pirátské listy ve střední části?

**Comment by Kedrigern** [comment]
Kalendář jsem vyměnil za klasický Google Cal, který používáme. Je tam celostátní. 

Otázky ohledně Toctify směřovat na jiné.

**Comment by Fafrin** [comment]
Super, ještě teda řešit jeho dobrou dostupnost z titulky.

**Comment by Kedrigern** [comment]
Co je špatného na kalendáři na titulce a odkazu na tu stránku?

**Comment by Fafrin** [comment]
Tak jsem našel odkaz na kalendář - je na konci sbalovacího tagu kalendáře.
Myslel bych si, že je důležitější a měl by být víš.
Ale teď to asi počká. Resp. je to celková otázka na UX a již nikoliv na funkčnost.
