### ISSUE TITLE
Špatní lidé v sekci lidé

### ISSUE THREAD

**Issue by Fafrin** [pirati-web/pirati.cz#41]
V sekci krajští zastupitelé a obecní radní se zobrazuje Robert Čuma, přestože není ani radní, ani krajský zastupitel.

Aneb sekce vybírá španě.

**Comment by Fafrin** [comment]
(Jsem si díval náhodně na názvy sekcí/týmů a chce to nějakej systém protože tohle je prostě chaos)

**Comment by jmichalek** [comment]
Mělo by to být uid
https://docs.google.com/document/d/1EOuaHp8eiTGP8Eoog_ZGgYxD40E3PJZYvswcZIJOJ3E/edit#

----
Mgr. et Mgr. Jakub Michálek,
předseda klubu Pirátů v zastupitelstvu hl. m. Prahy
jakub.michalek@pirati.cz, tel. 775 978 550

Česká pirátská strana
krajské sdružení Pirátů Praha
http://praha.pirati.cz

Upozornění: Týká-li se tato e-mailová zpráva jednání o smlouvě, bere její
adresát na vědomí, že v České pirátské straně podléhá uzavírání smluv
vnitřním předpisům a důvodné očekávání uzavření smlouvy je tak možné až po
souhlasu pověřeného orgánu. Vylučujeme přijetí nabídky s dodatkem nebo
odchylkou.

2017-03-21 18:32 GMT+01:00 Vojtěch Pikal <notifications@github.com>:

**Comment by Aktron** [comment]
otázka, určuje:

category:                 	# kategorie: rp, praha, vary, hradec, jmk, senat
- jmk

že člověk je z Brna nebo je to zastupitel z Jihomoravského kraje?

**Comment by Fafrin** [comment]
Mno, evidentně potřebujeme nějaký systém na pojmenovávání týmů, přičemž ten musí být platný napříč weby a systémy.
Navrhuju se přiměřeně opřít starý systém spisových značek.
JmK tedy znamená jihomoravský kraj - krajské sdružení jihomoravský kraj.
OlK by měl být olomoucký kraj
ZK_JmK by byl zastupitelský klub jihomoravského kraje
Olomouc by byl tým věnující se Olomouci jako městu
Ol_OlK je místní sdružení Olomouc
Praha je tým lidí věnujících se magistrátu prahy
Praha10 je tým lidí věnujících se zastupitelstvu Prahy 10
Pha je krajské sdružení praha
ZK_Praha je zastupitelský klub na magistrátu Prahy.
Mohlo by fungovat?

Související otázka - jsou profili lidí přenositelné/sdílitelné napříč weby, nebo si ho budu muset udržovat na 3+ místech?

**Comment by Kedrigern** [comment]
Přenositelné napříč jakými weby?

**Comment by Fafrin** [comment]
Podle všeho si máme vyrábět krajské weby.
Na krajském webu budu chtít mít taky profily lidí
Možná budeme občas vyrábět i dedikované volební weby (třeba v případě koalic)
I na volebním webu budu chtít mít profily lidí.

**Comment by Kedrigern** [comment]
Vezmu to oklikou:
1) Lidé na wiki také nebyli propojeni, protože téměř všichni (s výjimkou 2 krajů) používají volební weby. Někteří i stálé krajské. A to ještě v různých formátech (nikdo mimo docuwiki nepoužíval dokuwiki syntax)
2) Pokud máš volební web, měl bys mít přizpůsobený i text. Zvláště pak u těch koaličních.
3) V současnosti na některé věci používáme api: https://www.pirati.cz/api/ ,  čili to lze mít propojené. Ale nedělal bych to.

**Comment by Fafrin** [comment]
V tom případě teda mají být použity označení týmů skupin prostě podle potřeb hlavního webu.
Pokud teda api něco vhodně nepředepisuje, což ne.

**Comment by Fafrin** [comment]
navrhuju pro kraje (jako že krajské sdružení) používat označníky podle jejich .md
Pro zastupitelské týmy používat něco příhodného, tedy jihomoravsko pro krajský tým, JmK pro zastupitelský klub jihomoravského kraje.
Za mě už je to jak má být.
