### ISSUE TITLE
Medailonky sekci lidé problikávají moc rychle

### ISSUE THREAD

**Issue by vedlejedle** [pirati-web/pirati.cz#42]
Je to spíš detail, ale ty medilonky lidé v sekci lidé problikávají ta, že ho nestihneš dočíst natožpak kliknout na "celý profil". _Jistě člověk se může šipčičkou vrátit, ale to mi přijde, že je na běžného uživatele "moc práce".Navrhuji buď delší čas setrvání jednoho medailonku, nebo zkrátit popisy na úplně heslovité. Ale jak říkám, spíš detail, asi je dost věcí, co je potřeba vyřešit víc.

**Comment by Kedrigern** [comment]
Oprava: https://github.com/Kedrigern/pirati.cz , ale nejsou tam ke všem krajům ještě data. Prosím přidej je.
