### ISSUE TITLE
lepší 404

### ISSUE THREAD

**Issue by Fafrin** [pirati-web/pirati.cz#43]
nemohl bych dostat něco příjemnějšího, když zadám třeba pirati.cz/rules? -> https://www.pirati.cz/rules

**Comment by Kedrigern** [comment]
Samozřejmě, to není problém nastavit. Nejspíš by tam měl být základní statický rozcestník plus třeba jiný kontakt. Ale dnes už nemám sílu to udělat.

**Comment by jitka** [comment]
404 už existuje:
https://www.pirati.cz/404.html

Aby  fungovala musí se nastavit n nginx
https://jekyllrb.com/tutorials/custom-404-page/#hosting-on-nginx-server
