### ISSUE TITLE
Opravit odkaz "Makáme: Kalendář" ve footeru na stránce Otevřenost

### ISSUE THREAD

**Issue by lenoch** [pirati-web/pirati.cz#576]
Dobrý den,

na adrese https://www.pirati.cz/otevrenost/ máte ve footeru relativní odkaz `pripoj-se/kalendar`. Kvůli tomu dostávám 404. Patří tam `../`.

Asi je potřeba v https://github.com/pirati-web/pirati.cz/blob/gh-pages/otevrenost/index.html použít upravený layout, který zohlední, že stránka je na druhé úrovni.

**Comment by Fafrin** [comment]
Tak mělo by to vést sem - https://www.pirati.cz/pripoj-se/kalendar/

Vytvořil jsem fix, někdo se toho ujme.

**Comment by Fafrin** [comment]
Ok, vypadá to, že se mi to povedlo.
To člověka potěší na konci dne.
