### ISSUE TITLE
Na /program chybí CTA po dočtení

### ISSUE THREAD

**Issue by iBobik** [pirati-web/pirati.cz#68]
https://www.pirati.cz/program/

Po přečtení této stručné stránky učivatel může tápat kde se dočíst více. Nahoře u nadpisu to nenajde, protože to vypadá jako breadcrumbs (možné probémy i jinde).

Doporučuji pod seznam Prosazujeme přidat call-to-action (velké odkazy) na dlouhodobý program a kodex poslance.

**Comment by Kedrigern** [comment]
Asi by bylo dobré převzít CTA z kandidátek...

**Comment by jitka** [comment]
Call to action tam už tam je, jen tohle issue nikdo nezavřel.
``` Pokračujte na podrobný program pro všechny oblasti. Nebo se podívejte na celý program v PDF```
