### ISSUE TITLE
Nefunkční hledání na stránkách.

### ISSUE THREAD

**Issue by jitka** [pirati-web/pirati.cz#71]
Step to reproduce:
1. do políčka hledat hledání napišu "pirati"
2. zmačknu enter
3. kliknu na ikonu lupy

-> nic se nestane

Chromium Version 58.0.3029.96 (64-bit)
openSUSE 42.1

**Comment by Kedrigern** [comment]
Včéra jsem mergnul opravu, ale stále to není ideál. Nejméně by to mělo reagovat na enter.

**Comment by jitka** [comment]
Ondra na tom dělal na podzim. Povedlo se rozšířit našeptávač, lupa už vede na dug-dug-go ale enter stále nefunguje.
