### ISSUE TITLE
Graf na stránce s kalkulačkou ignoruje solidární daň

### ISSUE THREAD

**Issue by iBobik** [pirati-web/pirati.cz#72]
https://www.pirati.cz/kalkulacka/
![Graf](https://www.pirati.cz/assets/img/program/k03_mezni_sazby.png)

Graf ignoruje vliv solidární daně. Kalkulačka s ní počítá.

**Comment by jmichalek** [comment]
Ignoruje kde?

**Comment by iBobik** [comment]
Např. po zadání 150 000 do kalkulačky vyjde zdanění na 44 a 45%, graf ale u současného zdanění ukazuje 35%.

Jan Pobořil
http://honza.poboril.cz/

10. 6. 2017 v 23:33, Jakub Michálek <notifications@github.com>:

**Comment by jmichalek** [comment]
Není to chyba, jsou to jiná čísla. Graf ukazuje mezní sazbu (tj. zdanění stokoruny z příjmu v daném pásmu), v kalkulačce je zobrazeno efektivní zdanění (tj. zdanění celého příjmu).

**Comment by iBobik** [comment]
Aha, takže bych to nazval chybou v UX.

Možná pod ten graf napsat vysvětlení? Protože kdo se do této pasti dostane, tak asi bude hledat vysvětlení v textu kolem grafu.

Jan Pobořil
http://honza.poboril.cz/

11. 6. 2017 v 17:54, Jakub Michálek <notifications@github.com>:

**Comment by arius** [comment]
Je to chyba, pri prijmu nad 1.2M za rok se nasledne uplatnuje solidarni dan. Ta v grafu neni zohlednena.
Jak to mas napsane interne je jedno.
Z grafu ma uzivatel dojem, ze se jedna o miru zdaneni celeho prijmu podle jeho vyse. V tu chvili je ignorovani solidarni dane chybne.

**Comment by jmichalek** [comment]
Navrhni

----
Mgr. et Mgr. Jakub Michálek,
předseda klubu Pirátů v zastupitelstvu hl. m. Prahy
jakub.michalek@pirati.cz, tel. 775 978 550

Česká pirátská strana
krajské sdružení Pirátů Praha
http://praha.pirati.cz

Upozornění: Týká-li se tato e-mailová zpráva jednání o smlouvě, bere její
adresát na vědomí, že v České pirátské straně podléhá uzavírání smluv
vnitřním předpisům a důvodné očekávání uzavření smlouvy je tak možné až po
souhlasu pověřeného orgánu. Vylučujeme přijetí nabídky s dodatkem nebo
odchylkou.

Dne 11. června 2017 18:42 Jan Pobořil <notifications@github.com> napsal(a):

**Comment by Kedrigern** [comment]
Označuji jako invalid. Pokud někdo navrhnekonkrétní změnu, tak znovuotevřem.
