### ISSUE TITLE
Více možností zapojení

### ISSUE THREAD

**Issue by Fafrin** [pirati-web/pirati.cz#96]
Na stránkách pro podporu/zapojení ( https://www.pirati.cz/pripoj-se/ ) by bylo fajn přidat ještě odkazy na 

- Volné dobrovolnické pozice: pozice.jdem.cz

- Nabídku propagační plochy: objekty.jdem.cz

**Comment by Fafrin** [comment]
Tak, vyrobil jsem https://github.com/pirati-web/pirati.cz/pull/97
Co to dělá. Ja otázka případné následné diskuze s nějakým MO/markeťákem/PO jak to tam chce mít a jak by se to mělo jmenovat.

**Comment by Kedrigern** [comment]
Provedl jsem merge.
